### PR TITLE
Updated peer dependency

### PR DESCRIPTION
**Pull request by tareq0065**
every time we are trying to work with it causes a warning -
warning " > react-object-inspector@0.2.1" has incorrect peer dependency "react@^0.14.0".

### CODE REVIEW

**Comment by kraenhansen** [comment]
Yo @xyc - any change we can get this one merged?

**Comment by xyc** [comment]
@kraenhansen Do you mind using https://www.npmjs.com/package/react-inspector instead? it's more actively maintained and a drop-in replacement for `react-object-inspector`.

**Comment by kraenhansen** [comment]
Great! Thanks for sharing that - perhaps you could make this project deprecated in NPM to help others find `react-inspector`?

**Comment by xyc** [comment]
@kraenhansen thanks for the suggestion! I've updated deprecation notice in NPM

**Pull request closed without merging**
